name: blind
description: A vision assistance Flutter application.
publish_to: 'none'
version: 1.0.0+1
camera: ^0.10.5+9
path_provider: ^2.1.2
path: ^1.8.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_tts: ^4.2.3  # Text-to-speech
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
